name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'

    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt

    # - name: Start the application
    #   run: |
    #     nohup python app.py &
    #     sleep 10  # Wait for the application to start

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'https://ntfy.guggenbuehl.net'
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        format: 'html'
        output: 'zap_report.html'
        cmd_options: '-a'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap_report.html
